baseURL = "https://bl4cksqu4re.github.io"
languageCode = "ru-ru"
title = "Чёрный квадрат"
theme= "papermod"
defaultContentLanguage = 'ru'

[params]
mainSections = ["posts", "evento", "epitomoj"]
ShowShareButtons = true
ShareButtons = ["telegram", "twitter"]
ShowBreadCrumbs = true
enableRobotsTXT = true

[params.cover]
    linkFullImages = true

[languages]
    [languages.ru]
        title = 'Чёрный квадрат'
        [languages.ru.menu]
        [[languages.ru.menu.main]]
            name = 'дайджест'
            url = '/epitomoj'
            weight = 1
        [[languages.ru.menu.main]]
            name = 'мерч'
            url = '/varoj'
            weight = 1
        [[languages.ru.menu.main]]
            name = 'как добраться в квадрат'
            url = '/instrukcioj/agilo'
            weight = 1
        [[languages.ru.menu.main]]
            name = 'о нас'
            url = '/posts/resumo'
            weight = 2
        [[languages.ru.menu.main]]
            name = 'поддержать проект'
            url = '/helpo'
            weight = 3

        [[languages.ru.menu.main]]
            name = 'архив'
            url = '/archives/'
            weight = 5

        [[languages.ru.menu.main]]
            name = 'зин'
            url = '/revuoj/'
            weight = 4
	
	[[languages.ru.menu.main]]
	    name = 'меню'
            url = '/varoj/mangxoj'
            weight = 4

    [languages.eo]
        title = 'Nigra kvadrato'
        [languages.eo.menu]
        [[languages.eo.menu.main]]
            name = 'epitomo'
            url = '/epitomoj'
            weight = 0
        [[languages.eo.menu.main]]
            name = 'varo'
            url = '/varoj'
            weight = 0
        [[languages.eo.menu.main]]
            name = 'kiel atingi la kvadrato'
            url = '/instrukcioj/agilo'
            weight = 1    
        [[languages.eo.menu.main]]
            name = 'pri nin'
            url = '/posts/resumo'
            weight = 1
        [[languages.eo.menu.main]]
            name = 'archivo'
            url = '/archives/'
            weight = 4
        [[languages.eo.menu.main]]
            name = 'revuo'
            url = '/revuoj/'
            weight = 2
